#!/bin/bash

stuffthisneeds_dir=~/Documents/FFMPEG_test

if [ "$#" = 0 ] ; then
    echo "This script accepts input videos and generates outputs that include bars and tone at the head, plus a timecode track."
    echo "Usage: $(basename ${0}) [ -o output_directory ] fileorpackage1 [ fileorpackage2 ... ]"
    exit
fi

# command-line options to set mediaid and original variables
OPTIND=1
while getopts ":o:x:" opt ; do
    case "${opt}" in
        o) output_dir="$OPTARG" ;;
        x) audio_offset="$OPTARG" ;;
        *) echo "bad option -$OPTARG" ; usage ;;
        :) echo "Option -$OPTARG requires an argument" ; exit 1 ;;
    esac
done
shift $(( ${OPTIND} - 1 ))

input_movie="$1"
name=`basename "$input_movie"`
if [ ! -s "$input_movie" ] ; then
   echo Hey "$input_movie" does not look like a real file.
   exit
fi
if [ ! -d "$output_dir" ] ; then
   output_dir=`dirname "$input_movie"`
fi

if [ ! "$audio_offset" ] ; then
   audio_offset="0"
fi

bars="${stuffthisneeds_dir}/bars.mov"
tone="${stuffthisneeds_dir}/tone.wav"
if [ ! -s "$bars" ] ; then
   echo Hey the bars.mov file needs to be here "$bars".
   exit
fi
if [ ! -s "$tone" ] ; then
   echo Hey the tone.wav file needs to be here "$tone".
   exit
fi

ffmpeg -i "$tone" -i "$input_movie" -i "$bars" -itsoffset "${audio_offset}" -i "$input_movie" -filter_complex "[2:v:0]drawtext=fontsize=40:fontfile=/Library/Fonts/Courier New Bold.ttf:fontcolor=white:draw=gte(t\,30)*lt(t\,40):x=(w-text_w)/2:y=(h-text_h-line_h)/2:box=1:boxcolor=gray@0.9:text=${name%.*},format=yuv422p10le[bars];[bars][0:a:0][3:v:0][1:a:0]concat=n=2:v=1:a=1[v][a]" -shortest -map [a] -map [v] -c:v v210 -r 30000/1001 -timecode "00:59:15;00" -c:a pcm_s16le -ac 2 -ar 48000 -y "$output_dir/${name%.*}_ohyay2.mov"
